# Generated by Django 4.2.20 on 2025-04-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="watch",
            name="uuid",
            field=models.CharField(default="temp-uuid", max_length=100, unique=True),
        ),
    ]
