# Generated by Django 4.2.20 on 2025-04-16 01:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_watch_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watch",
            name="uuid",
        ),
    ]
