# Generated by Django 4.2.20 on 2025-04-27 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_watch_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watch",
            name="user",
            field=models.OneToOneField(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watch",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
