name: Deploy to EC2

on:
  push:
    branches:
      - main   # main 브랜치에 push될 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/watch-server
          git fetch origin
          git reset --hard origin/main
          sudo systemctl start postgresql 
          # 필요하면 서버 재시작 명령어 추가 (ex: pm2 restart, docker restart 등)
